/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorLock_indecation_SWC.h
 * Generated on: Tue Jun 24 19:17:58 EET
 ********************************************************************/

#ifndef RTE_DOORLOCK_INDECATION_SWC_H
#define RTE_DOORLOCK_INDECATION_SWC_H

#include "Rte_DoorLock_indecation_SWC_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_DoorLock_indecation_SWC * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_DoorLock_indecation_SWC * const Rte_Inst_DoorLock_indecation_SWC;

/************************ application errors *************************/

#define RTE_E_IF_CS_Led_E_OK ((Std_ReturnType)0)
#define RTE_E_IF_CS_Led_E_NOT_OK ((Std_ReturnType)1)

/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		RP_SR_DoorState
 * Interface:	IF_SR_DoorLock
 * DataElement:	DoorState
 * Runnable:	Door_Look_Indication
 *****************************************************/
extern myuint8 Rte_IRead_DoorLock_indecation_SWC_Door_Look_Indication_RP_SR_DoorState_DoorState (void);
#ifndef IN_RTE_C
#define Rte_IRead_Door_Look_Indication_RP_SR_DoorState_DoorState() \
	Rte_IRead_DoorLock_indecation_SWC_Door_Look_Indication_RP_SR_DoorState_DoorState()
#endif

/*****************************************************
 * Port: 		RP_CS_Led_Switch
 * Interface:	IF_CS_Led
 * Operation:	Led_Switch
 * Sync/Async:	Synchronous
 *****************************************************/
extern Std_ReturnType Rte_Call_DoorLock_indecation_SWC_RP_CS_Led_Switch_Led_Switch (myuint8 Led_State);
#ifndef IN_RTE_C
#define Rte_Call_RP_CS_Led_Switch_Led_Switch(Led_State) \
	Rte_Call_DoorLock_indecation_SWC_RP_CS_Led_Switch_Led_Switch(Led_State)
#endif


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	Door_Look_Indication
 * Period:		0.012
 *****************************************************/
extern void DoorLook_Indecation_runable(void);


/******** ARUnit-specific function pointers for server call delegates *********/
typedef Std_ReturnType (*FunctionPtr_DoorLock_indecation_SWC_RP_CS_Led_Switch_Led_Switch)(myuint8 Led_State);


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_DOORLOCK_INDECATION_SWC_H */
