/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorLock_indecation_SWC_Type.h
 * Generated on: Tue Jun 24 19:17:58 EET
 ********************************************************************/

#ifndef RTE_DOORLOCK_INDECATION_SWC_TYPE_H
#define RTE_DOORLOCK_INDECATION_SWC_TYPE_H


#include "Rte_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/*************************** range types *****************************/

#define myuint8_LowerLimit  (0U)
#define myuint8_UpperLimit (255U)

/************************ enumeration types **************************/



#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_DOORLOCK_INDECATION_SWC_TYPE_H */
