/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorLock_indecation_SWC_.c
 * Generated on: Wed Jun 25 9:32:9 EET
 ********************************************************************/

#include "string.h"
#include "Rte_DoorLock_indecation_SWC.h"


Rte_DE_myuint8 Door_Look_Indication_RP_SR_DoorState_DoorState;


const Rte_CDS_DoorLock_indecation_SWC Rte_Instance_DoorLock_indecation_SWC = {
&Door_Look_Indication_RP_SR_DoorState_DoorState
};

const Rte_CDS_DoorLock_indecation_SWC * const Rte_Inst_DoorLock_indecation_SWC = &Rte_Instance_DoorLock_indecation_SWC;


Std_ReturnType DoorLock_indecation_SWC_RP_CS_Led_Switch_Led_Switch_Buffer_retcode = RTE_E_OK;

FunctionPtr_DoorLock_indecation_SWC_RP_CS_Led_Switch_Led_Switch Rte_Call_DoorLock_indecation_SWC_RP_CS_Led_Switch_Led_Switch_Delegate = 0;

myuint8 Rte_IRead_DoorLock_indecation_SWC_Door_Look_Indication_RP_SR_DoorState_DoorState (void)
{
	return (Rte_Inst_DoorLock_indecation_SWC)->Door_Look_Indication_RP_SR_DoorState_DoorState->value;
}
Std_ReturnType Rte_Call_DoorLock_indecation_SWC_RP_CS_Led_Switch_Led_Switch (myuint8 Led_State)
{
	Std_ReturnType __result = DoorLock_indecation_SWC_RP_CS_Led_Switch_Led_Switch_Buffer_retcode;
	if ( Rte_Call_DoorLock_indecation_SWC_RP_CS_Led_Switch_Led_Switch_Delegate != 0 ) {
		__result = Rte_Call_DoorLock_indecation_SWC_RP_CS_Led_Switch_Led_Switch_Delegate(Led_State);
	}
	return __result;
}
