/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_DoorSensorAbstractionSWC.h
 * Generated on: Wed Jun 25 9:32:9 EET
 ********************************************************************/

#include "Rte_DoorSensorAbstractionSWC.h"	

#ifndef ARUNIT_DOORSENSORABSTRACTIONSWC_H
#define ARUNIT_DOORSENSORABSTRACTIONSWC_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef false
    #define false (0)
#endif
#ifndef true
    #define true  (!false)
#endif


void ARUnit_Initialize ();

/***************************************/
/******** Delegates API  ***************/
/***************************************/

/***************************************/
/******** Flags API  *******************/
/***************************************/

/***************************************/
/******** Implicit API  ****************/
/***************************************/
DECLSPEC_EXPORT void ARUnit_IWrite_DoorSensorAbstractionSWC_ReadDoorSensor_PP_SR_DoorState(myuint8 DoorState);
DECLSPEC_EXPORT myuint8 ARUnit_IRead_DoorSensorAbstractionSWC_ReadDoorSensor_PP_SR_DoorState(void);
DECLSPEC_EXPORT myuint8* ARUnit_IWriteRef_DoorSensorAbstractionSWC_ReadDoorSensor_PP_SR_DoorState(void);
/***************************************/
/******** Explicit API  ****************/
/***************************************/
/***************************************/
/******** Runnable Calls****************/
/***************************************/
DECLSPEC_EXPORT Std_ReturnType ARUnit_Trigger_DoorSensorAbstractionSWC_Led_Switch(myuint8 Led_State);

DECLSPEC_EXPORT void ARUnit_Trigger_DoorSensorAbstractionSWC_ReadDoorSensor_Runable(void);

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* ARUNIT_DOORSENSORABSTRACTIONSWC_H */
