/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_DoorSensorAbstractionSWC_.c
 * Generated on: Wed Jun 25 9:32:9 EET
 ********************************************************************/

#include "string.h"
#include "ARUnit_DoorSensorAbstractionSWC.h"


extern const Rte_CDS_DoorSensorAbstractionSWC Rte_Instance_DoorSensorAbstractionSWC;
extern const Rte_CDS_DoorSensorAbstractionSWC * const Rte_Inst_DoorSensorAbstractionSWC;




DECLSPEC_EXPORT void ARUnit_IWrite_DoorSensorAbstractionSWC_ReadDoorSensor_PP_SR_DoorState(myuint8 DoorState)
{
		(Rte_Inst_DoorSensorAbstractionSWC)->ReadDoorSensor_PP_SR_DoorState->value = DoorState;
}
DECLSPEC_EXPORT myuint8* ARUnit_IWriteRef_DoorSensorAbstractionSWC_ReadDoorSensor_PP_SR_DoorState(void)
{
	return &(Rte_Inst_DoorSensorAbstractionSWC)->ReadDoorSensor_PP_SR_DoorState->value;
}
DECLSPEC_EXPORT myuint8 ARUnit_IRead_DoorSensorAbstractionSWC_ReadDoorSensor_PP_SR_DoorState(void)
{
	return (Rte_Inst_DoorSensorAbstractionSWC)->ReadDoorSensor_PP_SR_DoorState->value;
}
DECLSPEC_EXPORT Std_ReturnType ARUnit_Trigger_DoorSensorAbstractionSWC_Led_Switch(myuint8 Led_State)
{
	return Led_Switch(Led_State);
}


DECLSPEC_EXPORT void ARUnit_Trigger_DoorSensorAbstractionSWC_ReadDoorSensor_Runable(void)
{
	ReadDoorSensor_Runable();
}
