/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_DoorLock_indecation_SWC_.c
 * Generated on: Wed Jun 25 9:32:9 EET
 ********************************************************************/

#include "string.h"
#include "ARUnit_DoorLock_indecation_SWC.h"


extern const Rte_CDS_DoorLock_indecation_SWC Rte_Instance_DoorLock_indecation_SWC;
extern const Rte_CDS_DoorLock_indecation_SWC * const Rte_Inst_DoorLock_indecation_SWC;


extern Std_ReturnType DoorLock_indecation_SWC_RP_CS_Led_Switch_Led_Switch_Buffer_retcode;

extern FunctionPtr_DoorLock_indecation_SWC_RP_CS_Led_Switch_Led_Switch Rte_Call_DoorLock_indecation_SWC_RP_CS_Led_Switch_Led_Switch_Delegate;

DECLSPEC_EXPORT void ARUnit_IWrite_DoorLock_indecation_SWC_Door_Look_Indication_RP_SR_DoorState_DoorState(myuint8 DoorState)
{
	(Rte_Inst_DoorLock_indecation_SWC)->Door_Look_Indication_RP_SR_DoorState_DoorState->value = DoorState;
}
DECLSPEC_EXPORT myuint8* ARUnit_IWriteRef_DoorLock_indecation_SWC_Door_Look_Indication_RP_SR_DoorState_DoorState(void)
{
	return &(Rte_Inst_DoorLock_indecation_SWC)->Door_Look_Indication_RP_SR_DoorState_DoorState->value;
}
DECLSPEC_EXPORT myuint8 ARUnit_IRead_DoorLock_indecation_SWC_Door_Look_Indication_RP_SR_DoorState_DoorState(void)
{
	return (Rte_Inst_DoorLock_indecation_SWC)->Door_Look_Indication_RP_SR_DoorState_DoorState->value;
}
DECLSPEC_EXPORT void ARUnit_Call_DoorLock_indecation_SWC_RP_CS_Led_Switch_Led_Switch_ReturnCode(Std_ReturnType returnCode)
{
	DoorLock_indecation_SWC_RP_CS_Led_Switch_Led_Switch_Buffer_retcode = returnCode;
}

DECLSPEC_EXPORT void ARUnit_Set_DoorLock_indecation_SWC_RP_CS_Led_Switch_Led_Switch_Delegate(FunctionPtr_DoorLock_indecation_SWC_RP_CS_Led_Switch_Led_Switch  delegate)
{
	Rte_Call_DoorLock_indecation_SWC_RP_CS_Led_Switch_Led_Switch_Delegate = delegate;
}

DECLSPEC_EXPORT void ARUnit_Trigger_DoorLock_indecation_SWC_DoorLook_Indecation_runable(void)
{
	DoorLook_Indecation_runable();
}
